{% set version="0.9.9" %}

build:
  number: 0

about:
  home: https://github.com/seqan/seqan/blob/develop/apps/yara/README.rst
  license: https://raw.githubusercontent.com/seqan/seqan/develop/apps/yara/LICENSE
  summary: Yara is an exact tool for aligning DNA sequencing reads to reference genomes.

package:
  name: yara
  version: {{ version }}

source:
  - url:  http://packages.seqan.de/yara/yara-{{ version }}-Mac-x86_64.zip # [osx]
    sha256: 716230b2f2b147e1d6db7aba017adcf668484436aa7541228776c23b0c5f52a2 # [osx]
    fn: yara-{{ version }}-Mac-x86_64.zip # [osx]
    folder: x64 # [osx]
  - url: http://packages.seqan.de/yara/yara-{{ version }}-Mac-x86_64_sse4.zip # [osx]
    sha256: 429d30ba47161a8d28fa9c4875d76e746f6c4fb520b61285df760d8e2982df63 # [osx]
    fn: yara-{{ version }}-Mac-x86_64_sse4.zip # [osx]
    folder: sse4 # [osx]
  - url: http://packages.seqan.de/yara/yara-{{ version }}-Linux-x86_64.tar.xz # [linux64]
    sha256: b8c6fac0481a3438eeb34a5d1330dd73af8fcc1febdf84adba6058a820323da0 # [linux64]
    fn: yara-{{ version }}-Linux-x86_64.tar.xz # [linux64]
    folder: x64 # [linux64]
  - url: http://packages.seqan.de/yara/yara-{{ version }}-Linux-x86_64_sse4.tar.xz # [linux64]
    sha256: 1893162e088a383e10c6b9e97bce81671be19020fecf82666663a632d36fa1c6 # [linux64]
    fn: yara-{{ version }}-Linux-x86_64_sse4.tar.xz # [linux64]
    folder: sse4 # [linux64]

test:
  commands:
    - yara_indexer --help 2>&1 > /dev/null
    - yara_mapper --help 2>&1 > /dev/null