{% set version="0.9.9" %}
{% set seqan_version="2.3.2" %}

build:
  number: 0
  skip: True  # [not linux]

about:
  home: https://github.com/seqan/seqan/blob/develop/apps/yara/README.rst
  license: https://raw.githubusercontent.com/seqan/seqan/develop/apps/yara/LICENSE
  summary: Yara is an exact tool for aligning DNA sequencing reads to reference genomes.

package:
  name: yara
  version: {{ version }}

source:
  fn: seqan-v{{ seqan_version }}.tar.gz
  url: https://github.com/seqan/seqan/archive/seqan-v{{ seqan_version }}.tar.gz
  sha256: 73ce4b344e6a259db1518547544c730f548bc0b32292b30e3a027146e158085e

requirements:
  build:
    - binutils_impl_linux-32 ==2.28.1 # [linux32]
    - binutils_impl_linux-64 ==2.28.1 # [linux64]
    - binutils_linux-32 ==7.2.0 # [linux32]
    - binutils_linux-64 ==7.2.0 # [linux64]
    - bzip2 ==1.0.6
    - ca-certificates ==2017.08.26
    - cmake ==3.9.1
    - curl ==7.55.1
    - expat ==2.2.4
    - gcc_impl_linux-32 ==7.2.0 # [linux32]
    - gcc_impl_linux-64 ==7.2.0 # [linux64]
    - gcc_linux-32 ==7.2.0 # [linux32]
    - gcc_linux-64 ==7.2.0 # [linux64]
    - gxx_impl_linux-32 ==7.2.0 # [linux32]
    - gxx_impl_linux-64 ==7.2.0 # [linux64]
    - gxx_linux-32 ==7.2.0 # [linux32]
    - gxx_linux-64 ==7.2.0
    - libgcc-ng ==7.2.0
    - libssh2 ==1.8.0
    - libstdcxx-ng ==7.2.0
    - libuv ==1.14.0
    - make ==4.2.1
    - ncurses =={{ CONDA_NCURSES }}*
    - openssl ==1.0.2l
    - rhash ==1.3.5
    - xz ==5.2.3
    - zlib =={{ CONDA_ZLIB }}*

test:
  commands:
    - yara_indexer --help 2>&1 > /dev/null
    - yara_mapper --help 2>&1 > /dev/null
