{% set version = "1.2.4" %}

package:
  name: "clustalo"
  version: "{{ version }}"

source:
  url: http://www.clustal.org/omega/clustal-omega-1.2.4.tar.gz
  md5: 6c0459f4c463a30e942ce7e0efc91422

requirements:
    build:
        - gcc
        - argtable2

build:
    number: 0

test:
    commands:
        - "clustalo --help > /dev/null"

about:
    home: "http://www.clustal.org/omega/"
    license: "GPLv2"
    summary: "Latest version of Clustal: a multiple sequence alignment program for DNA or proteins"
