package:
  name: perl-tk
  version: "804.034"

source:
  fn: Tk-804.034.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.034.tar.gz
  md5: 213bf9e575b0697953f65c34093598c0

build:
  number: 0

requirements:
  build:
    - perl {{ CONDA_PERL }}*
    - perl-encode
    - perl-extutils-makemaker
    - perl-test-simple
    - libpng >=1.6.28,<1.7
    - xorg-libx11 # [not osx]
    #- xorg-libxft
    - libjpeg-turbo
    # - libfreetype  - disabled, set XFT=0 in Makefile

  run:
    - perl {{ CONDA_PERL }}*
    - perl-encode
    - libpng >=1.6.28,<1.7
    - perl-test-simple
    - tk # [not osx]
    - xorg-libx11 # [not osx]

test:
  # Perl 'use' tests
  commands:
    - perl -e 'use Tk'

about:
  home: http://metacpan.org/pod/Tk
  license: unrestricted
  summary: 'Tk - a Graphical User Interface Toolkit'
